<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>UniversalSteamMetadata</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWPF>True</UseWPF>
    <TargetFramework>net462</TargetFramework>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <OsirisDevelopmentRoot Condition="'$(OsirisDevelopmentRoot)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\..\Programming\Development\Osiris</OsirisDevelopmentRoot>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <None Update="extension.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="icon.png" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Localization\**\*" CopyToOutputDirectory="PreserveNewest" />
    <None Update="SteamShared\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Playnite.SDK">
      <HintPath>$(OsirisDevelopmentRoot)\App\Playnite.SDK.dll</HintPath>
    </Reference>
    <Reference Include="AngleSharp">
      <HintPath>$(OsirisDevelopmentRoot)\App\AngleSharp.dll</HintPath>
    </Reference>
    <Reference Include="SteamKit2">
      <HintPath>$(OsirisDevelopmentRoot)\Data\Extensions\Metadata\UniversalSteamMetadata_f2db8fb1-4981-4dc4-b087-05c782215b72\SteamKit2.dll</HintPath>
    </Reference>
    <Reference Include="System.Core" />
    <Reference Include="PresentationCore" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Web" />
  </ItemGroup>
</Project>
