<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>Osiris.SteamGridDBMetadata</AssemblyName>
    <RootNamespace>Osiris.Extensions.SteamGridDBMetadata</RootNamespace>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <UseWPF>True</UseWPF>
    <TargetFramework>net462</TargetFramework>
    <EnableDefaultApplicationDefinition>false</EnableDefaultApplicationDefinition>
    <LangVersion>latest</LangVersion>
    <OsirisDevelopmentRoot Condition="'$(OsirisDevelopmentRoot)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\..\Programming\Development\Osiris</OsirisDevelopmentRoot>
  </PropertyGroup>
  <ItemGroup>
    <None Update="extension.yaml" CopyToOutputDirectory="PreserveNewest" />
    <None Update="icon.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="Playnite.SDK">
      <HintPath>$(OsirisDevelopmentRoot)\App\Playnite.SDK.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Newtonsoft.Json">
      <HintPath>$(OsirisDevelopmentRoot)\App\Newtonsoft.Json.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
  </ItemGroup>
</Project>
