namespace Playnite.Native;

public enum DISPLAYCONFIG_COLOR_ENCODING : uint
{
	DISPLAYCONFIG_COLOR_ENCODING_RGB = 0u,
	DISPLAYCONFIG_COLOR_ENCODING_YCBCR444 = 1u,
	DISPLAYCONFIG_COLOR_ENCODING_YCBCR422 = 2u,
	DISPLAYCONFIG_COLOR_ENCODING_YCBCR420 = 3u,
	DISPLAYCONFIG_COLOR_ENCODING_INTENSITY = 4u,
	DISPLAYCONFIG_COLOR_ENCODING_FORCE_UINT32 = uint.MaxValue
}
