namespace Playnite.Native;

public enum DISPLAYCONFIG_DEVICE_INFO_TYPE : uint
{
	DISPLAYCONFIG_DEVICE_INFO_GET_SOURCE_NAME = 1u,
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_NAME = 2u,
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_PREFERRED_MODE = 3u,
	DISPLAYCONFIG_DEVICE_INFO_GET_ADAPTER_NAME = 4u,
	DISPLAYCONFIG_DEVICE_INFO_SET_TARGET_PERSISTENCE = 5u,
	DISPLAYCONFIG_DEVICE_INFO_GET_TARGET_BASE_TYPE = 6u,
	DISPLAYCONFIG_DEVICE_INFO_GET_SUPPORT_VIRTUAL_RESOLUTION = 7u,
	DISPLAYCONFIG_DEVICE_INFO_SET_SUPPORT_VIRTUAL_RESOLUTION = 8u,
	DISPLAYCONFIG_DEVICE_INFO_GET_ADVANCED_COLOR_INFO = 9u,
	DISPLAYCONFIG_DEVICE_INFO_SET_ADVANCED_COLOR_STATE = 10u,
	DISPLAYCONFIG_DEVICE_INFO_GET_SDR_WHITE_LEVEL = 11u,
	DISPLAYCONFIG_DEVICE_INFO_GET_MONITOR_SPECIALIZATION = 12u,
	DISPLAYCONFIG_DEVICE_INFO_SET_MONITOR_SPECIALIZATION = 13u,
	DISPLAYCONFIG_DEVICE_INFO_FORCE_UINT32 = uint.MaxValue
}
